
## Week 4: Practical in Geographic Data Analysis


#### Loading data from a CSV file into a DataFrame

* ```pandas.read_csv( )``` ---
[read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv) can accept a filename or URL as an argument.

set the global variable ```WC_DF``` to a DataFrame containing the information from ```worldcities.csv```.

The data contains a variety of information about cities from around the world.

In [2]:
import pandas

WC_DF = pandas.read_csv("worldcities.csv")

#### Checking the contents of a DataFrame

In [3]:
WC_DF.head(15)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
5,Delhi,Delhi,28.6700,77.2300,India,IN,IND,Delhi,admin,15926000.0,1356872604
6,Shanghai,Shanghai,31.2165,121.4365,China,CN,CHN,Shanghai,admin,14987000.0,1156073548
7,Kolkata,Kolkata,22.4950,88.3247,India,IN,IND,West Bengal,admin,14787000.0,1356060520
8,Los Angeles,Los Angeles,34.1139,-118.4068,United States,US,USA,California,NaN,12815475.0,1840020491
9,Dhaka,Dhaka,23.7231,90.4086,Bangladesh,BD,BGD,Dhaka,primary,12797394.0,1050529279
10,Buenos Aires,Buenos Aires,-34.6025,-58.3975,Argentina,AR,ARG,"Buenos Aires, Ciudad Autónoma de",primary,12795000.0,1032717330
11,Karachi,Karachi,24.8700,66.9900,Pakistan,PK,PAK,Sindh,admin,12130000.0,1586129469
12,Cairo,Cairo,30.0500,31.2500,Egypt,EG,EGY,Al Qāhirah,primary,11893000.0,1818253931
13,Rio de Janeiro,Rio de Janeiro,-22.9250,-43.2250,Brazil,BR,BRA,Rio de Janeiro,admin,11748000.0,1076887657
14,Ōsaka,Osaka,34.7500,135.4601,Japan,JP,JPN,Ōsaka,admin,11294000.0,1392419823

In [4]:
WC_DF.describe()

                lat           lng    population            id
count  15493.000000  15493.000000  1.380800e+04  1.549300e+04
mean      29.633315    -29.834189  1.812480e+05  1.623208e+09
std       22.414727     76.340457  7.947989e+05  2.826451e+08
min      -54.933300   -179.590000  0.000000e+00  1.004003e+09
25%       22.305000    -86.324200  9.167500e+03  1.404601e+09
50%       37.756200    -71.916700  2.349650e+04  1.826644e+09
75%       42.444200     25.582100  9.030625e+04  1.840015e+09
max       82.483300    179.383300  3.567600e+07  1.934000e+09

In [5]:
WC_DF[WC_DF["city"] == "Tokyo"]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.685,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764

In [12]:
WC_DF[WC_DF["city"] == "Paris"]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
19,Paris,Paris,48.8667,2.3333,France,FR,FRA,Île-de-France,primary,9904000.0,1250015082
9170,Paris,Paris,33.6689,-95.5462,United States,US,USA,Texas,NaN,25961.0,1840020594
11195,Paris,Paris,38.2016,-84.2719,United States,US,USA,Kentucky,NaN,12662.0,1840014315
11815,Paris,Paris,36.2933,-88.3065,United States,US,USA,Tennessee,NaN,10576.0,1840014438
12546,Paris,Paris,39.6148,-87.6905,United States,US,USA,Illinois,NaN,8431.0,1840009542
14992,Paris,Paris,44.2445,-70.4883,United States,US,USA,Maine,NaN,5148.0,1840052952

In [11]:
WC_DF[WC_DF["city"] == "Paris"][WC_DF["country"] == "France"]

/var/folders/f0/kp_djvw53dsbyvwrx6zgsw900000gn/T/ipykernel_1217/3530764999.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  WC_DF[WC_DF["city"] == "Paris"][WC_DF["country"] == "France"]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
19,Paris,Paris,48.8667,2.3333,France,FR,FRA,Île-de-France,primary,9904000.0,1250015082

In [13]:
WC_DF[  WC_DF['lat']>5  ][:5]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
5,Delhi,Delhi,28.6700,77.2300,India,IN,IND,Delhi,admin,15926000.0,1356872604

In [14]:
top_5_cities = WC_DF["city"][:5]   ## selects the first 5 items of the "city" column.
top_5_cities

0          Tokyo
1       New York
2    Mexico City
3         Mumbai
4      São Paulo
Name: city, dtype: object

One difference with lists is that for Series objects the index label of each element can be different kinds of values

e.g. alphabetic letters:

In [15]:
top_5_cities.index = list(top_5_cities)
top_5_cities["Tokyo"]

'Tokyo'

In [16]:
my_list = [1,2,3,4,5]
my_list[0]

1

In [17]:
top_5_cities["a"]

KeyError: 'a'

In [18]:
top_5_cities.index

Index(['Tokyo', 'New York', 'Mexico City', 'Mumbai', 'São Paulo'], dtype='object')

In [19]:
WC_DF.index

RangeIndex(start=0, stop=15493, step=1)

You can also use ```.values``` to return an `array` of the column values without
the index:

In [22]:
import numpy as np
cities_array = WC_DF["population"].values
# print(np.mean(cities_array))

nan

In [21]:
WC_DF.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id'],
      dtype='object')

__Note:__ `Index` is another type of list-like object, similar to a series and an array but used exclusively for holding labels to index a `Series` or `DataFrame`.

Usually just treat `Series`, `array` and `Index` objects like lists. Also if you want to change them to an ordinary list you can use the `list` operator

In [9]:
list(WC_DF.columns)

['city',
 'city_ascii',
 'lat',
 'lng',
 'country',
 'iso2',
 'iso3',
 'admin_name',
 'capital',
 'population',
 'id']

We can refer to rows of a `DataFrame` either by the expression `DF.loc[label]`, where `label` is the index label of the row we want, or by `DF.iloc[n]`, where `n` is an `int` giving the position of the row in the `DataFrame`.



In the case of `WC_DF`, the labels are integers, so we would get the same result using either.

In [55]:
WC_DF.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519

In [63]:
top_5_cities.head()

Tokyo                Tokyo
New York          New York
Mexico City    Mexico City
Mumbai              Mumbai
São Paulo        São Paulo
Name: city, dtype: object

In [64]:
top_5_cities.iloc[0]

'Tokyo'

In [57]:
var = WC_DF.iloc[1]
WC_DF.loc[1]

city               New York
city_ascii         New York
lat                 40.6943
lng                -73.9249
country       United States
iso2                     US
iso3                    USA
admin_name         New York
capital                 NaN
population       19354922.0
id               1840034016
Name: 1, dtype: object

#### Iterrating through the rows of a DataFrame
Using the `iterrows` method in a `for` loop.

In [65]:
WC_DF

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
15488,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
15489,Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

In [11]:
for i, row in WC_DF.iterrows():
    print(i, row['city_ascii'], row['lat'], row['lng'])
    if i >3: break

0 Tokyo 35.685 139.7514
1 New York 40.6943 -73.9249
2 Mexico City 19.4424 -99.131
3 Mumbai 19.017 72.857
4 Sao Paulo -23.5587 -46.625

#### Sorting the rows of a DataFrame using ```.sort_values```

In [68]:
WC_DF.sort_values(by=["country", "city"], ascending=True)[:100] # Sorts countries by alphabet

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
7399,Andkhōy,Andkhoy,36.9317,65.1015,Afghanistan,AF,AFG,Fāryāb,minor,71730.0,1004472345
3945,Asadābād,Asadabad,34.8660,71.1500,Afghanistan,AF,AFG,Kunaṟ,admin,48400.0,1004251962
4512,Aībak,Aibak,36.2610,68.0400,Afghanistan,AF,AFG,Samangān,admin,24000.0,1004564619
1976,Baghlān,Baghlan,36.1393,68.6993,Afghanistan,AF,AFG,Baghlān,minor,218748.0,1004943705
2261,Balkh,Balkh,36.7501,66.8997,Afghanistan,AF,AFG,Balkh,minor,179969.0,1004654094
...,...,...,...,...,...,...,...,...,...,...,...
15106,I-n-Amguel,I-n-Amguel,23.6939,5.1647,Algeria,DZ,DZA,Tamanrasset,NaN,3030.0,1012162135
7937,I-n-Salah,I-n-Salah,27.2166,2.4666,Algeria,DZ,DZA,Tamanrasset,NaN,49223.0,1012201146
5113,Illizi,Illizi,26.4834,8.4666,Algeria,DZ,DZA,Illizi,admin,7957.0,1012499058
2600,Jijel,Jijel,36.8220,5.7660,Algeria,DZ,DZA,Jijel,admin,148000.0,1012782547
5482,Khenchela,Khenchela,35.4358,7.1433,Algeria,DZ,DZA,Khenchela,admin,NaN,1012495148

##### Note on __encodings__ of the city name
[Unicode characters](https://home.unicode.org/) encoded using [UTF-8](https://en.wikipedia.org/wiki/UTF-8)

and [ASCII](https://en.wikipedia.org/wiki/ASCII) code, which uses a single byte per character.

#### Filtering DataFrames
_filtering_ means keeping some parts and throwing away others.
Typically based on rows values that match some conditions
Pandas `DataFrame` can  be filtered according values of a column by using a boolean expression, for example:

In [69]:
WC_DF['capital'] == 'admin'

0        False
1        False
2        False
3         True
4         True
         ...
15488    False
15489    False
15490    False
15491    False
15492    False
Name: capital, Length: 15493, dtype: bool

In [13]:
filtered_DF = WC_DF[ WC_DF['capital'] == 'admin'] # This keeps only administrative capitals
filtered_DF.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
5,Delhi,Delhi,28.6700,77.2300,India,IN,IND,Delhi,admin,15926000.0,1356872604
6,Shanghai,Shanghai,31.2165,121.4365,China,CN,CHN,Shanghai,admin,14987000.0,1156073548
7,Kolkata,Kolkata,22.4950,88.3247,India,IN,IND,West Bengal,admin,14787000.0,1356060520

How it works:
*  `DF['label']` (where `DF` is any `DataFrame`), gives a `Series` corresponding
    to    the `'label'` column of `DF.
    
*  `a_series == val` or a Boolean operator (such `==`, `<` etc.) is applied to a `Series` object
   the result is actually a `Series` of Boolean values `True` for each element where
   the original `Series` satisfies `element == val`, and `False` for the rest.
   
* `DF[ bool_series ]`, is an operation, where a boolean
   series is given as a selection argument to the `DataFrame`. It will return 
   a new DF, containing all the rows of `DF` for which `bool_series` has the 
   value `True`

### Several tasks...

#### Pre-processing the data
* __A__ --- Find all city names that include *non-ASCII* characters.

* __B__ --- Find city names that occur multiple times in the dataset.

#### Filtering / extracting data of interest
* __C__ --- Create a `DataFrame` of the largest cities (by population) in the world.
* __D__  --- Find all cities in a given country whose population is above a given number.
* __E__ --- Find the total population of people living in cities in a given country.

### A
Some cities include accents or symbols that are not represented in the standard ASCII character set. Write a function `non_ascii_cities`, which returns a `Set` containing all the cities that occur in the `world_cities.csv` dataset whose name cannot be properly represented using only ASCII characters.

In [70]:
WC_DF

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
15488,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
15489,Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

In [78]:
# A

def non_ascii_cities():
    cities = WC_DF[ WC_DF['city_ascii'] != WC_DF['city']  ]
    print(len(cities['city']), len(set(cities['city'])))
    return set(cities['city'])

non_ascii_cities()

1889 1851

{'Toltén',
 'Thiès',
 'Sfântu-Gheorghe',
 'Eiði',
 'Kérouané',
 'Samaná',
 'N’Djamena',
 'Ingeniero Guillermo N. Juárez',
 'Kamen’-na-Obi',
 'Béziers',
 'Kermān',
 'Ñacunday',
 'Hachiōji',
 'Sveti Jurij ob Ščavnici',
 'Štip',
 'Zābol',
 'Goianésia',
 'Paranaguá',
 'Ch’ŏngjin',
 'Guajará-Mirim',
 'Grudziądz',
 'Sonīpat',
 'Potosí',
 'Obleševo',
 'Murang’a',
 'Tômbua',
 'Kocēni',
 '‘Ajmān',
 'Gusinoozërsk',
 'Ciudad de Huajuapam de León',
 'Plzeň',
 'Shaḩḩāt',
 'Jyväskylä',
 'Zveçan',
 'Melitopol’',
 'Birgañj',
 'Al Fallūjah',
 'Río Gallegos',
 'Žabljak',
 'Bắc Giang',
 'Dahūk',
 'Trollhättan',
 'Mellieħa',
 'Dhangaḍhi̇̄',
 'Székesfehérvár',
 'Saïda',
 'Tərtər',
 'Hachimanchō',
 'Vyaz’ma',
 'Karūr',
 'Caacupé',
 'Ba‘qūbah',
 'Aračinovo',
 'Itaberaí',
 'Dubăsari',
 'Žetale',
 'Los Ángeles',
 'Nālūt',
 'Herāt',
 'Yên Bái',
 'Cap-Haïtien',
 'Għargħur',
 'Néma',
 'Gjøvik',
 'Trípoli',
 'Say’ūn',
 'Saint Ann’s Bay',
 'Al Ḩasakah',
 'Barra do Garças',
 'Changyŏn',
 'Nāsik',
 'Čaška',
 'Şa‘dah',
 'Rogašovci',
 'Roslavl’',
 'Malmö',
 'Tórshavn',
 'Río Grande',
 'Vevčani',
 'Sŏnbong',
 'Nek’emtē',
 'Sankt Pölten',
 'Añatuya',
 'Carúpano',
 'Santa Maria da Vitória',
 'San Cristóbal',
 'Vadsø',
 'Mitrovicë',
 'Mingəçevir',
 'Roboré',
 'Marabá',
 'Chiquinquirá',
 'Yaroslavl’',
 'Poljčane',
 'Jáltipan de Morelos',
 'Samandağ',
 'Curicó',
 'Bălţi',
 'Paysandú',
 'Cobán',
 'Łutselk’e',
 'São José dos Campos',
 'Évora',
 'Tržič',
 'Focşani',
 'Alexandroúpoli',
 'Győr',
 'Kramators’k',
 'Óbidos',
 'Al ‘Alamayn',
 'Fuglafjørður',
 'Tāngāil',
 'Zinjibār',
 'Mezen’',
 'Shar’ya',
 'Québec',
 'Aqtöbe',
 'Mişrātah',
 'Setúbal',
 'Toruń',
 'Gorišnica',
 'Brežice',
 'Shibīn al Kawm',
 'Banhā',
 'Birāṭnagar',
 'Cà Mau',
 'Ma’rib',
 'Perm’',
 'Al Kūt',
 'São Luís',
 'Šentjernej',
 'Concepción del Uruguay',
 'Negēlē',
 'Dajabón',
 'Bezwāda',
 'Jérémie',
 'Žužemberk',
 'Hamadān',
 'Şırnak',
 'La Unión',
 'Oğuz',
 'Ruše',
 'Haymā’',
 'Bīkaner',
 'Aḑ Ḑab‘ah',
 'Prokop’yevsk',
 'Şirvan',
 'Rača',
 'Berdyans’k',
 'Orël',
 'Gdańsk',
 'El’dikan',
 'N’dalatando',
 'Itajaí',
 'Çorovodë',
 'Ra’s al Khaymah',
 'Spassk-Dal’niy',
 'Marília',
 'Tuyên Quang',
 'Straža',
 'Ağdam',
 'Žagubica',
 'Kavála',
 'Halachó',
 'Ródos',
 'Garça',
 'Zākhū',
 'San José',
 'Črnomelj',
 'Calheta de São Miguel',
 'L’gov',
 'Simferopol’',
 'Črenšovci',
 'Divača',
 'Târgu Jiu',
 'Rečica ob Savinji',
 'Mandalī',
 'Mörön',
 'Maltahöhe',
 'Durrës',
 'Al ‘Uqaylah',
 'Villazón',
 'Thakhèk',
 'Juradó',
 'Växjö',
 'Biržai',
 'Piatra Neamţ',
 'Căuşeni',
 'Rugāji',
 'Gīmbī',
 'Karbalā’',
 'São Francisco do Sul',
 'Puerto Limón',
 'Paraíso',
 'Vänersborg',
 'Nyköping',
 'Colón',
 'Ning’an',
 'Taxco de Alarcón',
 'Valparaíso',
 'Hînceşti',
 'Astrakhan’',
 'Tamuín',
 'Elazığ',
 'Shāhrūd',
 'Zərdab',
 'Corumbá',
 'Skúvoy',
 'Spárti',
 'San Pedro de Macorís',
 'Coalcomán de Vázquez Pallares',
 'Kupiškis',
 'Jaú',
 'San Ramón de la Nueva Orán',
 'Tucuruí',
 'Gyêgu',
 'Uşak',
 'Fámjin',
 'Jõhvi',
 'Jequié',
 'Polatlı',
 'Lambaréné',
 'Gəncə',
 'Sežana',
 'Brăila',
 'Orūmīyeh',
 'Ålesund',
 'Atakpamé',
 'Saarbrücken',
 'Klaksvík',
 'Rājahmundry',
 'Pāvilosta',
 'Ciego de Ávila',
 'Villa Martín Colchak',
 'Torreón',
 'Tønsberg',
 'Mengeš',
 'Ísafjörður',
 'Lashkar Gāh',
 'Nāgpur',
 'Āsosa',
 'Beyləqan',
 'Qaşr al Farāfirah',
 'Aiguá',
 'Sabzevār',
 'Petatlán',
 'Söke',
 'Białystok',
 'Rače',
 'Zalău',
 'Veszprém',
 'Lübeck',
 'Neyshābūr',
 'Kārsava',
 'Al Manāqil',
 'Pájaros',
 'Viļaka',
 'Ćuprija',
 'Thái Bình',
 'Rørvik',
 'Codó',
 'Alatyr’',
 'Fu’an',
 'Minamiōzuma',
 'Hāgere Hiywet',
 'Āksum',
 'Nabatîyé',
 'Torbat-e Jām',
 'Bhiwāni',
 'Fushë Kosovë',
 'Neuquén',
 'Muğla',
 'Puerto López',
 'Irákleio',
 'Constitución',
 'Miragoâne',
 'Tver’',
 'Cəbrayıl',
 'Apače',
 'Ştefan Vodă',
 'Icó',
 'Andkhōy',
 'Trenčín',
 'Val-d’Or',
 'Constanţa',
 'Copiapó',
 'Xin’an',
 'Kpalimé',
 'Río Colorado',
 'Rîşcani',
 'São João da Boa Vista',
 'Pathānkot',
 'Kyŏngju',
 'Nar’yan-Mar',
 'São Tomé',
 'Delémont',
 'Ağstafa',
 'Ribeirão Prêto',
 'Bāglung',
 'Thủ Dầu Một',
 'Catalão',
 'Atoyac de Álvarez',
 'Al Qurayyāt',
 'Seinäjoki',
 'Moravče',
 'Kahramanmaraş',
 'Hà Tĩnh',
 'Wé',
 'Grajaú',
 'Shemonaīkha',
 'Ta’ Xbiex',
 'Šentjur',
 'Babušnica',
 'Dunaújváros',
 'Suharekë',
 'Sunch’ŏn',
 'Ust’-Kuyga',
 'Galaţi',
 'Zreče',
 'Sīkar',
 'Quinhámel',
 'Kelmė',
 'Taubaté',
 'Ar Rayyān',
 'Joaçaba',
 'Amrāvati',
 'An Cabhán',
 'Pinar del Río',
 'Hŭngnam',
 'Aţ Ţā’if',
 'Baghlān',
 'Širvintos',
 'Tomaž pri Ormožu',
 'Šilalė',
 'Macará',
 'Konče',
 'Pervoural’sk',
 'Ghāt',
 'Žabari',
 'Nevel’sk',
 'Būlaevo',
 'Żurrieq',
 'Thái Nguyên',
 'Khromtaū',
 'Goiânia',
 'Şūr',
 'Vị Thanh',
 'Aydın',
 'Ploieşti',
 'Mālegaon',
 'Ébolowa',
 'Béja',
 'Marawī',
 'Tacuarembó',
 'Castellón de la Plana',
 'Qal‘ah-ye Now',
 'Mohale’s Hoek',
 'Dezfūl',
 'Rokiškis',
 'Morón',
 'Borlänge',
 'Guaíra',
 'Makīnsk',
 'Pointe-à-Pitre',
 'Derzhavīnsk',
 'Zürich',
 'Telšiai',
 'Machilīpatnam',
 'Pul-e Khumrī',
 'Preševo',
 'Rrëshen',
 'Krāslava',
 'Anápolis',
 'Antsiran̈ana',
 'Saint John’s',
 'Aībak',
 'Chīrāla',
 'Poços de Caldas',
 'Ubá',
 'Khorramābād',
 'Ust’-Nyukzha',
 'Skrīveri',
 'San Ramón',
 'Araranguá',
 'Eirunepé',
 'Pećinci',
 'Ji-Paraná',
 'Jönköping',
 'Vlorë',
 'Severo-Kuril’sk',
 'Bač',
 'Ḩajjah',
 'Dīla',
 'Varėna',
 'Ngaoundéré',
 'Canatlán',
 'Aïn Sefra',
 'Río Mayo',
 'Ciudad Lázaro Cárdenas',
 'Balsadero Río Verde',
 'Straşeni',
 'Viļāni',
 'Qəbələ',
 'Kosjerić',
 'Dhamār',
 'Faīẕābād',
 'Al Qaşr',
 'Užice',
 'Mežica',
 'Sīwah',
 'Diyarbakır',
 'Tekirdağ',
 'Inírida',
 'Sovetskaya Gavan’',
 'Fürth',
 'Al ‘Aqabah',
 'Bacău',
 'Tébessa',
 'Brčko',
 'Ta‘izz',
 'Dhūlia',
 'Qŭrghonteppa',
 'Santo Tomás',
 'Vólos',
 'Radeče',
 'Šabac',
 'Qūchān',
 'Timbaúba',
 '‘Ibrī',
 'Juchitán de Zaragoza',
 'Covilhã',
 'Ivančna Gorica',
 'Chascomús',
 'Ludhiāna',
 'Marāgheh',
 'Santo Ângelo',
 'Farāh',
 'Lívingston',
 'Severoural’sk',
 'Ust’-Ilimsk',
 'Itambé',
 'Volčja Draga',
 'Floreşti',
 'Port Saint John’s',
 'Guamúchil',
 'Tillabéri',
 'Sørum',
 'Salgótarján',
 'Rondonópolis',
 'Abunã',
 'Västerås',
 'Irecê',
 'Akmenė',
 'Semič',
 'Belčišta',
 'Ciudad Guzmán',
 'Hanumānnagar',
 'Ấp Đa Lợi',
 'Shchëkino',
 'Guaratinguetá',
 'Ełk',
 'Şuşa',
 'Januária',
 'Pagėgiai',
 'Pančevo',
 'Liège',
 'Alīgarh',
 'Ust’-Ordynskiy',
 'Luján',
 'Batočina',
 'Bafoulabé',
 'Al Qaţīf',
 'Kukës',
 'Ar Ramādī',
 'Dembī Dolo',
 'Hamhŭng',
 'Odienné',
 'Sevastopol’',
 'Ersekë',
 'Hà Giang',
 'Botoşani',
 'Središče ob Dravi',
 'Ioánnina',
 'Sal’sk',
 'Ul’kan',
 'Bīdar',
 'Shashemenē',
 'Acapulco de Juárez',
 'Desē',
 'Ağsu',
 'Alausí',
 'N’Zérékoré',
 'Kattaqo‘rg‘on',
 'Qubadlı',
 'Satupa‘itea',
 'Heydərabad',
 'Ibrā’',
 'Atyraū',
 'Prešov',
 'Ayagöz',
 'Jirjā',
 'Svolvær',
 'Piteşti',
 'Pakxé',
 'Sūrat',
 'Ocniţa',
 'Sauðárkrókur',
 'Kürdəmir',
 'Bijāpur',
 'Concepción',
 'Liquiçá',
 'Örebro',
 'Ústí nad Labem',
 'San Pedro de Ycuamandiyú',
 'Roatán',
 'Godē',
 'Phan Thiết',
 'Jaboatão',
 'Sept-Îles',
 'Stari Trg pri Ložu',
 'Sansanné-Mango',
 'Raška',
 'Preiļi',
 'Tepelenë',
 'Sodražica',
 'Bački Petrovac',
 'Artëmovskiy',
 'Tobol’sk',
 'Ḩadībū',
 'Komotiní',
 'Mahābād',
 'Córdoba',
 'Kırklareli',
 'Krasnoural’sk',
 'Nikšić',
 'Edéa',
 'Sīrjān',
 'Şəki',
 'Khakhar’',
 'Quibdó',
 'Cataño',
 'Chapecó',
 'Butwāl',
 'Délįne',
 'Poznań',
 'Braşov',
 'Petrópolis',
 'Juárez',
 'Hāthras',
 'Eséka',
 'Siġġiewi',
 'Caracaraí',
 'Pukë',
 'Mirzāpur',
 'São Gabriel da Cachoeira',
 'Linköping',
 'Lào Cai',
 'Al Fayyūm',
 'Khōst',
 'Técpan de Galeana',
 'São José do Rio Prêto',
 'Cáceres',
 'Mytilíni',
 'Ārba Minch’',
 'Ciudad Nezahualcóyotl',
 'Bagé',
 'San Quintín',
 'Limbaži',
 'Dehra Dūn',
 'Arkhangel’sk',
 'Orocué',
 'Zárate',
 'Muş',
 'Viðareiði',
 'Lātūr',
 'Mūrmuiža',
 'L’viv',
 'Rūjiena',
 'P’yŏngsan',
 'Laçın',
 'Strenči',
 'Eşfahān',
 'Bījār',
 'Črna na Koroškem',
 'Ferreñafe',
 'Gümüşhane',
 'As Salţ',
 'Palmeira dos Índios',
 'Krško',
 'Ḩafar al Bāţin',
 'Al Minyā',
 'Estância',
 'Şuḩār',
 'Sokodé',
 'Crateús',
 'Šid',
 'Al’met’yevsk',
 'Coronel Suárez',
 'Bhāvnagar',
 'Požega',
 'Balakən',
 'Stavropol’',
 'Ropaži',
 'Nouméa',
 'Zāhedān',
 'Egilsstaðir',
 'Mallawī',
 'Açu',
 'Villa Constitución',
 'Würzburg',
 'Araxá',
 'Gießen',
 'Zanjān',
 'Pont-y-pŵl',
 'Lənkəran',
 'Ash Shiḩr',
 'Shibirghān',
 'Cárdenas',
 'Žitište',
 'Šmartno pri Litiji',
 'Kolhāpur',
 'Burhānpur',
 'Hödrögö',
 'Sayḩūt',
 'Ciudad Obregón',
 'Bollnäs',
 'Sāveh',
 'Mazatlán',
 'Noyabr’sk',
 'Dal’nerechensk',
 'Nazrēt',
 'Tehuacán',
 'Probištip',
 'Ağcabədi',
 'São João del Rei',
 'Jūrmala',
 'Labé',
 'Ivano-Frankivs’k',
 'Nev’yansk',
 'Arāk',
 'Fernandópolis',
 'Saint-Étienne',
 'Östersund',
 'Jamālpur',
 'Starše',
 'Kem’',
 'Araçatuba',
 'Al Jabīn',
 'Al ‘Arīsh',
 'Buôn Ma Thuột',
 'Varāmīn',
 'Jāzān',
 'Macapá',
 'Jaqué',
 'Guantánamo',
 'Angra do Heroísmo',
 'Tây Ninh',
 'Čajetina',
 'Guaxupé',
 'As Suwaydā’',
 'Gambēla',
 'Al Qāmishlī',
 'Pīlibhīt',
 'Minatitlán',
 'Laḩij',
 'Ciudad Cortés',
 'Cañon City',
 'Nuquí',
 'Šavnik',
 'Vitória',
 'Wrocław',
 'Bingöl',
 'Merošina',
 'Bol’sheretsk',
 'Popayán',
 'Shīeli',
 'Šalovci',
 'Pátra',
 'Mālpils',
 'Škofja Loka',
 'Al Bāḩah',
 'Ghardaïa',
 'Abdurahmoni Jomí',
 'Mataró',
 'Santa Inês',
 'Khmel’nyts’kyy',
 'Karnāl',
 'Sétif',
 'Kam”yanets’-Podil’s’kyy',
 'Pärnu',
 'Zelënodol’sk',
 'Tarīn Kōṯ',
 'Vaiņode',
 'Araguaína',
 'Saint-Jérôme',
 'Sārī',
 'Chŏngju',
 'Kök-Janggak',
 'Kamensk-Ural’skiy',
 'Safājā',
 'Bejaïa',
 'Tubarão',
 'Oktyabr’skiy',
 'Batī',
 'Đà Lạt',
 'Hưng Yên',
 'Cuauhtémoc',
 'Yélimané',
 'Palé',
 'Ōsaka',
 'Türkmenbaşy',
 'Jalālābād',
 'Đồng Hới',
 'Călăraşi',
 'Ibagué',
 'Lar’yak',
 'Nong’an',
 'Dəvəçi',
 'Saint Paul’s Bay',
 'Vilkaviškis',
 'Timişoara',
 'Jēkabpils',
 'Änew',
 'Río Bueno',
 'Caçador',
 'Porto Inglês',
 'Banī Suwayf',
 'Kvívík',
 'Gouré',
 'Bà Rịa',
 'Kamenicë',
 'Beočin',
 'Rivière-du-Loup',
 'Mārupe',
 'Alto Río Senguer',
 'Bāramūla',
 'Bhairāhawā',
 'Kishkeneköl',
 'Fdérik',
 'Anykščiai',
 'Niquelândia',
 'Priekuļi',
 'Adıyaman',
 'Tocantinópolis',
 'Bečej',
 'Peñuelas',
 'Cần Thơ',
 'Mazatán',
 'Bắc Ninh',
 'Cao Bằng',
 'Ürümqi',
 'Bodø',
 'Shtërpcë',
 'Banī Walīd',
 'Rostuša',
 'Īlām',
 'Tokār',
 'Gia Nghĩa',
 'Jumlā',
 'Zavrč',
 'Hải Dương',
 'Iğdır',
 'Veržej',
 'As Samāwah',
 'Gabú',
 'Ghāziābād',
 'Şoldăneşti',
 'Barnīs',
 'Tecomán',
 'Tam Kỳ',
 'Çorum',
 'Zlín',
 'Bərdə',
 'Kovel’',
 'Cēsis',
 'Fès',
 'Štore',
 'Żejtun',
 'Kateríni',
 'Podol’sk',
 'Deçan',
 'Bāmyān',
 'Jaén',
 'Kolār',
 'Kırıkkale',
 'Garzón',
 'Piraçununga',
 'Krasnotur’insk',
 'Türkistan',
 'Komsomol’sk-na-Amure',
 'Marsá Maţrūḩ',
 'Novobërdë',
 'Göyçay',
 'Dyat’kovo',
 'Ikšķile',
 'Nyíregyháza',
 'Zaječar',
 'Vecvārkava',
 'Anouvông',
 'Çankırı',
 'Klinë',
 'San Julián',
 'Bhāgalpur',
 'Itanhaém',
 'Puerto Aysén',
 'Siteía',
 'Macaé',
 'Godāwari̇̄',
 'Al Hufūf',
 'Santa Bárbara',
 'Araçuaí',
 'Zhangaözen',
 'Besançon',
 'Srīnagar',
 'Jhānsi',
 'Manatí',
 'Xocalı',
 'Maués',
 'Bhātpāra',
 'Acaraú',
 'Lysychans’k',
 'Târgovişte',
 'Niš',
 'Tāluqān',
 'Kökshetaū',
 'Autlán de Navarro',
 'Tatuí',
 'Borūjerd',
 'Švenčionys',
 'Juršinci',
 'La Cañada Flintridge',
 'Kŭlob',
 'Guntūr',
 'Vyshniy Volochëk',
 'An Nuhūd',
 'İzmir',
 'Ust’-Kamchatsk',
 'Fayrōz Kōh',
 'Bento Gonçalves',
 'Babanūsah',
 'Râmnicu Vâlcea',
 'Rāichūr',
 'Neuchâtel',
 'Kemijärvi',
 'Qarataū',
 'Mocímboa',
 'Ħamrun',
 'Qəzyan',
 'Sopište',
 'Ilha de Moçambique',
 'Barakī Barak',
 'Portimão',
 'Želino',
 'Koné',
 'Kəlbəcər',
 'P’ungsan',
 'Sumqayıt',
 'Ts’khinvali',
 'Xánthi',
 'Kākināda',
 'Usulután',
 'San José de las Lajas',
 'Čačak',
 'Villa O’Higgins',
 'Varaždin',
 'Hòa Bình',
 'Puerto Carreño',
 'Abéché',
 'Barisāl',
 'Elbląg',
 'Masjed Soleymān',
 'Shīrāz',
 'Šmarješke Toplice',
 'Ardabīl',
 'Bogué',
 'Inčukalns',
 'Joaquín V. González',
 'Nikopol’',
 'Al Qunayţirah',
 'Thanh Hóa',
 'Tân An',
 'Lạng Sơn',
 'Būrylbaytal',
 '‘Amrān',
 'Divinópolis',
 'Wādī Ḩalfā’',
 'Wŏnsan',
 'Hódmezővásárhely',
 'Gospić',
 'São Filipe',
 'Yong’an',
 'Tuluá',
 'Kawm Umbū',
 'Târgu-Mureş',
 'Trois-Rivières',
 'Füzuli',
 'Penonomé',
 'Nizāmābād',
 'Plungė',
 'Olenëk',
 'Salacgrīva',
 'Tauragė',
 'Šentilj',
 'Nīlī',
 'Beppuchō',
 'Capitão Poço',
 'Nova Varoš',
 'Nepālgañj',
 'Aḑ Ḑāli‘',
 'Semnān',
 'São José dos Pinhais',
 'Hämeenlinna',
 'Kaçanik',
 'Criciúma',
 'Mirbāţ',
 'Vitória da Conquista',
 'Hāora',
 'Rāmechhāp',
 'São José de Ribamar',
 'Aïn Temouchent',
 'Göygöl',
 'Rožaje',
 'Guayaramerín',
 'Chitré',
 'Rạch Giá',
 'Korçë',
 'Syzran’',
 'Al Ḩazm',
 'Medinīpur',
 'Nova Viçosa',
 'San Martín',
 'Podujevë',
 'Yi’an',
 'Santa Vitória do Palmar',
 'Chaniá',
 'Žilina',
 'Chānda',
 'Lüderitz',
 'Colíder',
 'San Ġiljan',
 'Tiruppūr',
 'Āwasa',
 'Iaşi',
 'Imġarr',
 'Brocēni',
 'Riebiņi',
 'Tauá',
 'Ghadāmis',
 'Al ‘Ayn',
 'Guéckédou',
 'Kraków',
 'Al Bayḑā’',
 'Culiacán',
 'Namp’o',
 'Totonicapán',
 'São Domingos',
 'Béni Mellal',
 'Ust’-Olenëk',
 'Siyəzən',
 'Al Khārijah',
 'Soubré',
 'Žiri',
 'São Paulo',
 'Ust’-Maya',
 'Morādābād',
 'Inđija',
 'Gabès',
 'Az Zaqāzīq',
 'San-Pédro',
 'Bouaké',
 'Kolašin',
 'Tiruvannāmalai',
 'Teleneşti',
 'Oriximiná',
 'Asyūţ',
 'Séguéla',
 'Ad Dammām',
 'Ḩā’il',
 'Léo',
 'Kruševo',
 'Nīca',
 'Ust’-Kut',
 'Asunción',
 'Al Ghayz̧ah',
 'Juanjuí',
 'Żebbuġ',
 'P’yŏngsŏng',
 'Fīrozābād',
 'Phônsavan',
 'Long Xuyên',
 'Qıvraq',
 'João Pessoa',
 'Uman’',
 'Anadyr’',
 'Tabrīz',
 'Maiquetía',
 'Abhā',
 'Orléans',
 'An Nāşirīyah',
 'Tefé',
 ...}

In [80]:
cities = []
for i, row in WC_DF.iterrows():
    if row['city'] in cities:
        print(row['city'])
    cities.append(row['city'])

Suzhou
Santiago
Vila Velha
Natal
Valencia
Yichun
Birmingham
Xiping
Barcelona
Al Ḩillah
Tripoli
Lancaster
London
Mérida
San Juan
Fayetteville
Córdoba
Victoria
Springfield
Jining
Crato
Reading
Salem
Columbus
Concord
Fuzhou
Santa Ana
Noginsk
Arlington
Córdoba
Portland
Glendale
Cartagena
Aurora
Huntington
Norwich
La Paz
San Cristóbal
Santa Cruz
Vancouver
Baicheng
Takaoka
Fuyang
Peoria
Salamanca
Manchester
Alexandria
Nakhodka
Springfield
Lafayette
York
Gainesville
San Cristóbal
Kansas City
Hamilton
Panama City
Brest
Charleston
Pasadena
Santa Maria
Athens
Columbia
León
Cartago
San Luis
Saint John’s
Greenville
Worcester
Santa Clara
San Fernando
Rochester
Bloomington
Kingston
Cambridge
Santa Rosa
Manzanillo
Santa Fe
Richmond
Dali
Jacksonville
Burlington
Escuintla
Granada
San Antonio
Columbia
Westminster
Peterborough
Formosa
Lakewood
Toledo
San Juan
Wilmington
Santa Rosa
Concepción
Medford
Mérida
Trujillo
Lakewood
Alexandria
Valladolid
Middelburg
Everett
Santiago
Arlington
Salem
Concord
Perth
Montclair
San José
Dover
Belleville
Bragança
Chester
Long Beach
Spring Valley
San Pablo
Oceanside
San Carlos
Oak Park
Santarém
San Fernando
Englewood
Burbank
Brandon
Santa Cruz
Soledad
Levittown
Belmont
University Park
San Lorenzo
San Fernando
Maywood
Elmwood Park
Albany
Hawthorne
Viseu
Ceres
Dover
Mao
La Paz
Brownsville
San Francisco
Zamora
San Carlos
Four Corners
Huntington
Kingston
Salisbury
Somerville
Mwanza
Santa Bárbara
Valparaíso
Greenville
Maywood
Trujillo
Bristol
Brentwood
Sinop
Four Corners
Bellevue
Maplewood
San Lorenzo
Riverside
Guadalupe
San Carlos
Prospect Park
Norwood
Plymouth
Bellevue
Edgewater
Glendale
South Pasadena
Salinas
Santa Bárbara
Hartford
Groningen
Dover
La Palma
Al Bayḑā’
San Juan
Kensington
Santiago
San Jose
Rochester
Newport
Ibb
Worcester
Uppsala
Lincoln
Newport
Derby
Trinidad
Busia
San Fernando
Belfast
Victoria
Halifax
Fontana
Solothurn
Elgin
Richmond
San Fernando
Safi
Picos
Scarborough
Durham
Bor
Jincheng
Kon Tum
Rabat
Hamilton
Trindade
Santa Cruz
Dimitrovgrad
Gombe
Lubango
Tottori
Żebbuġ
Guadalupe
Armavir
Požega
Winchester
Tarrafal
Santana
Perm’
San Jose
Călăraşi
Rio Claro
Irvine
Loja
Navoiy
Georgetown
Altay
Mahdia
Lakewood
Middletown
Lawrence
San Marcos
Aurangābād
Mandeville
Portsmouth
Portsmouth
Dover
Lafayette
Florence
Albany
Hamilton
Norwalk
Decatur
Jackson
Bloomington
Springfield
Alexandria
Melbourne
Linares
Warwick
Auburn
Parma
Newark
Plymouth
Florence
Folsom
Anderson
Bethlehem
Union City
Darhan
San Marcos
Winchester
Jackson
Lodi
Guadalajara
Cleveland
Georgetown
Bristol
Lima
Mount Vernon
Hammond
Mansfield
Decatur
Victoria
Oktyabr’skiy
Middletown
Longview
Wellington
Gloucester
Colón
Kayes
Brentwood
Springfield
Hamilton
Fairfield
Rome
Dublin
Albany
San Fernando
Morristown
Lakewood
Bristol
Linares
San Felipe
Midland
Bangor
San Rafael
San Francisco
Columbus
Plymouth
San Pedro
Manchester
Manhattan
Taunton
Jackson
Kingston
Union
Caldwell
Leesburg
Pamplona
Brookhaven
Lewiston
Bellevue
Wheaton
Mercedes
Stratford
Jaén
Apple Valley
Hamilton
Levittown
St. Cloud
Smyrna
Troy
Bedford
Wilson
Roswell
Monroe
Madison
Lawrence
Tuckahoe
Palm Springs
Lincoln
San Lorenzo
Dublin
Newark
Roseville
Carrollton
Danville
Qingyuan
Beaumont
Middletown
Parma
Quincy
Danville
Farmington
Mount Pleasant
Enfield
Lancaster
Plainfield
Salinas
Monroe
Manchester
Linden
Clovis
Brentwood
Fairfield
Spring Hill
Richmond
Greenwood
Berkeley
Belleville
Marion
Bartlett
Maplewood
Oviedo
Brighton
Richmond
Amherst
Warren
Huntsville
Westfield
Marion
Lancaster
Orange
Kirov
Palmas
Germantown
Tønsberg
Enterprise
Columbia
Wheeling
Meridian
Brookfield
Sydney
London
Mount Pleasant
Monrovia
San Juan
Greenfield
Brighton
Shrewsbury
Portage
Portsmouth
Dunedin
Roseville
Franklin
Shawnee
Martinez
Georgetown
Paradise
Chelmsford
Monroe
Bethlehem
Coventry
Brunswick
Oswego
Auburn
Riviera Beach
Sanford
Cumberland
Carmel
Middletown
Lebanon
Deer Park
Schaffhausen
Newark
Salisbury
Franklin
Northbrook
Lexington
Derry
Salina
Lawrence
Gaya
Andover
Plainfield
Carlsbad
Warsaw
St. Charles
Bowling Green
Florence
Oxford
Parkland
Rome
Columbus
Redmond
Villarrica
Cicero
Falmouth
Greenville
Des Moines
Auburn
Pingxiang
Río Grande
Rochester
Fair Oaks
Mercedes
San Luis
Clinton
Springfield
Spring Valley
Westfield
Texarkana
Gloucester
Moanda
Livingston
Milton
Athens
Castro
Kent
Highland Park
Saratoga Springs
Syracuse
Fitchburg
Duluth
Rotterdam
O'Fallon
Sanford
Athens
Cornelius
Geneva
Norwood
Oak Ridge
Aberdeen
Windsor
Salem
Burlington
Henderson
Northampton
Harrison
Jacksonville
Lacey
Sunbury
Aberdeen
Hobart
Princeton
Gaoua
Lansing
Canton
Sterling
Deer Park
Independence
Windsor
Fremont
Milton
Pasadena
New Milford
Gladstone
Lewes
Norfolk
Stafford
Wakefield
Garden City
Mount Pleasant
Albany
Lafayette
Lebanon
Washington
La Unión
Medina
Burlington
Laurel
Mansfield
Winchester
Paris
Randolph
Troy
Salem
Woodstock
Reading
Madison
Farmington
Moscow
Lockport
Windsor
Austin
Midlothian
Lancaster
Clinton
Victoria
Riverside
Franklin
Greenville
Newport
Socorro
Lincoln
Somerset
Westmont
Ontario
Burlington
Victoria
Fresno
Freeport
Thomasville
Erie
Marysville
Plainview
Hudson
Medford
Farmington
Easton
Brandon
Conway
Mansfield
Derby
Wilmington
Pelham
Medford
Gitega
Oakdale
Watertown
Columbus
Farmington
Montgomery
Auburn
Venice
Saginaw
Pittsburg
Hastings
Kenmore
Oxford
Canton
Roselle
New Brighton
Garden City
Highland
Winchester
Fremont
Vernon
Auburn
Edgewater
Bloomington
Waynesboro
Summit
Bristol
Hudson
Clarksburg
Greenfield
Bedford
Bloomingdale
Geneva
Augusta
Watertown
Clinton
Chester
Naples
New Castle
Watertown
Lakeside
Marietta
Darien
Belton
Mount Vernon
Clarksville
La Porte
Lincoln
Smithfield
Johnston
Jacksonville
Lebanon
Palatka
Johnstown
Clayton
Union City
Amsterdam
Ardmore
Lexington
Shelbyville
Oxford
Birmingham
Louisville
Ashland
Arnold
Trinidad
Selma
Charleston
Covington
Essex
Milford
Grand Island
Alexandria
Bloomfield
San Felipe
Ashland
Shelbyville
Gardner
Murray
Lebanon
Greenwood
Berlin
Norwalk
Brunswick
Dublin
Evans
Newton
Dickinson
Ashland
Harvey
Montclair
Salamanca
Ogden
Henderson
Clifton
Germantown
Ottawa
Hudson
Forest Park
Monroe
Punta Gorda
Cameron Park
Montgomery
Durango
Scarborough
Lake Forest
Baldwin
Danville
Sherwood
Bethany
Montville
Stillwater
Concord
Shelton
Carlisle
Arlington
Waterford
Milton
Homewood
Helena
Orange
Frankfort
Ennis
Highland
White Oak
Grandview
Cherry Hill
Monroe
Lexington
Altoona
Marshfield
Sudbury
Forest Park
Bay City
Westminster
Niles
Nara
Avon
Arcadia
Aberdeen
Stafford
Cudahy
Somerset
Trenton
Madison
Pembroke
Middelburg
Manchester
El Dorado
Shenandoah
New Castle
Franklin Park
Madison
Bedford
Berea
Huntington
Ada
Cary
Sovetsk
Salem
Fayetteville
Springfield
Marion
Easton
Windham
Centerville
Concord
Ferndale
Rosedale
Avon
Maitland
Springfield
Īlām
Colonia
Ashland
Portsmouth
Same
Veinticinco de Mayo
Lincoln
Mesquite
Portland
Alton
Versailles
Shorewood
Laurel
Dallas
Brookfield
Wayne
Florence
Bellingham
Batavia
Bella Vista
Morris
Wilton
Washington
Bristol
Troy
Burlington
Buffalo
Mercedes
Mount Pleasant
Seymour
Auburn
Vienna
Centralia
Westchester
Douglas
Dixon
Evans
San Martín
Athens
Gainesville
Monroe
Durham
Washington
Taylor
Middletown
Frankfort
San Gabriel
Aberdeen
Madison
Colchester
Warren
Aurora
Belgrade
Westport
Parma
Harrisburg
Miami
Bellevue
La Grange
Mount Vernon
Long Beach
Great Falls
Lebanon
New Haven
Pembroke
Washington
Alamo
Newton
Aarau
Cambridge
Addison
Griffith
McMinnville
Hereford
Damascus
Hampton
Junín
Fullerton
Milford
Gainesville
Glasgow
Jamestown
Ramsey
Sterling
Cambridge
Englewood
Weston
Plainfield
Troy
Hartford
Salyan
Las Vegas
Berea
College Park
Cleveland
Jackson
Cambridge
Bedford
Brooklyn Park
Graham
Park City
Canton
Harrison
Ijevan
Exeter
Henderson
Forest City
El Dorado
Pleasanton
London
Franklin Park
Warren
Johnson City
Lindenhurst
Oak Park
Hanover
Crowley
Jacksonville
Ascensión
Payson
Kingston
Windham
Hanover
Cambridge
Washington
Antioch
Camden
Lebanon
Livingston
Bedford
Harrison
Mountain Home
Covington
Ferndale
Conway
Bridgetown
Orange
Canton
Douglas
Hendersonville
Springdale
Lewisville
Oxford
Glasgow
Richmond
Clinton
Arcadia
Uxbridge
Ipswich
Hutchinson
Whitehall
Thompson
Seabrook
Monroe
Verona
Warrington
Washington
Lyndhurst
West Haven
Swansea
Marshall
Englewood
Artesia
Newark
Santa Fe
Jasper
Kent
Lockhart
Newington
Van Buren
Riverdale
San Marino
Pelham
Franklin
Dayton
Kettering
Sharon
Dallas
Oakland
Clayton
Kingston
Georgetown
Washington
Andover
Verona
Newton
Worthington
Stoughton
Clinton
Lakeside
Rochester
Marion
Martinsville
Chelsea
Rogers
Maryville
Oxford
Lawrenceburg
Superior
Trenton
Farmington
Greenville
York
Horsham
Lumberton
Bastrop
Riverton
Loveland
Dover
Glendale
Frederick
Paris
Charlotte
Mount Vernon
Florence
Peru
Boone
Bedford
Lakeland
Jacksonville
Derby
Jackson
Parker
Corinth
Brunswick
Cornwall
Hudson
Coventry
Oregon
Marion
Fredericksburg
Marysville
Plymouth
Lumberton
Gulfport
Warwick
Jefferson
Marshall
Warwick
Wilmington
Gladstone
Pontiac
Woolwich
Freeport
Athens
Clayton
Ottawa
Lansdowne
Riverview
Amherst
Richmond
Belmont
Leeds
Weston
Portland
Norton
Rehoboth
Manchester
Elgin
Patterson
Greensburg
Lansing
Holly Springs
Somerset
Georgetown
Stafford
Garden City
Plymouth
Berkley
Falmouth
Newport
Otsego
Portland
Largo
Nelson
Port Washington
Red Bank
Newton
Franklin
Martinsville
Weatherford
Richfield
Eureka
Newcastle
Arlington
Ozark
Norfolk
Bridgeton
Grafton
Winchester
Dudley
Delhi
Sandy
Plano
Elizabethtown
Smyrna
Cottage Grove
Evanston
Jackson
Hillsborough
Ravenna
Bradford
Grove City
Ridgefield
Hanover
Highland
East Windsor
Smithfield
Fairfield
Belén
Berlin
Newport
Westwood
Fulton
Delémont
Urbana
Somers
Leicester
Santa Cruz
Beachwood
Shiloh
Lakeville
Amherst
Canyon Lake
Springdale
Edgewood
Niles
Yorktown
Summerfield
Clinton
Madison Heights
Lewisburg
Woodland Park
Damascus
Webster
Woodmere
Brookings
Woodbury
Holbrook
Urbana
Highland Park
Norwalk
Manchester
Winchester
Crestwood
Forestville
Brooklyn
Spencer
Milton
Florence
Waterford
Montgomery
New Albany
Selma
Point Pleasant
Hudson
Whitehall
Fairfield
Monroe
Decatur
Myrtle Grove
Hillsdale
Farmington
Paris
Seymour
Exeter
Smithfield
Cleveland
Oak Hills
Portage
Scituate
Warren
Summerville
Jefferson
Lincoln Park
Southport
Norton
Santiago
Lawrenceburg
Columbia
Beverly Hills
Richmond Heights
Covington
Dayton
Clearfield
Oak Grove
Alpine
Vienna
Anderson
Weston
Brookhaven
Canton
Camden
East Greenwich
Barrington
Columbia
Southampton
Reading
Georgetown
Lowell
Lexington
Fairview
Lancaster
Troy
Kirkland
Princeton
Waterloo
Pleasant Grove
Clinton
Ontario
Bluffton
Hartsville
Greenville
Sparta
Independence
Conway
Milton
Grafton
Vernon
Sweetwater
Woodbury
Country Club
Edgewater
Northampton
Philipsburg
Pleasant Hill
Croydon
Franklin
Union City
Burlington
Danville
Chillicothe
Union
Littleton
Russellville
Marysville
Garden City
Hamburg
Greenville
Winfield
Monticello
Middleton
Mooresville
Waterford
Clay
Potsdam
Bryan
New Baltimore
Mount Holly
Howell
Winslow
Jennings
Lantana
Oxford
Warrenton
Augusta
Alexandria
Springfield
Wellington
Clinton
Mount Airy
Little Falls
Mission
Westwood
Fayetteville
Marlton
Redlands
La Plata
Union
Amherst
Louisville
Victoria
Fairview
Logan
Monmouth
Laurel
Lynwood
Middletown
Brandon
Cairo
Bloomingdale
Elwood
Lowell
Red Bank
Highland Park
Brownsville
Corozal
Sullivan
Indianola
St. Marys
Harrisburg
Independence
Fair Oaks
Beverly Hills
Plymouth
Meadowbrook
Fairmont
Groton
Ayr
Brunswick
Greenwood
Chester
White City
Salisbury
Shelby
Audubon
Bridgewater
Olney
Plainville
Franklin
Garden City
Fairview
Park Ridge
Live Oak
Sheffield
Chatham
Memphis
Berkeley
Oakville
Plymouth
Villas
St. Albans
La Grange
Hamilton
Lexington
Wesley Chapel
Waverly
Seabrook
Kearney
Graham
Seaside
Midland
Quincy
Burlington
Woodburn
Franklin
Riverdale
Pineville
Riverside
Commerce
Livingston
Edgewood
Heath
Stuttgart
Clayton
Clinton
Elsmere
Rockland
Bridgeport
Monroe
Princeton
Laurel
Dumbarton
Morrisville
Georgetown
Wyoming
Clinton
Willowbrook
Yarmouth
Lake City
Pleasant Hill
Corning
Monticello
Gonzales
Mount Pleasant
McFarland
Carbondale
Sheridan
Kensington
Paris
Oakland
Mason
Greenville
Riverside
Socorro
Chester
Covington
Richmond Heights
St. Joseph
Northfield
York
Jefferson City
Murphy
Aurora
Savannah
Bath
Lansdowne
Johnstown
Denison
Fairmount
Hillsboro
Williamsburg
Irondale
Bloomingdale
Milton
Salem
Ashland
Clinton
Whitestown
Bellevue
Burton
Alliance
Trinidad
Roanoke
Oak Grove
Montrose
Cedar Hills
Hillside
Brookhaven
Jefferson
Long Branch
Ripon
Brentwood
Hamilton
Logan
Odessa
Shorewood
Albion
Princeton
Salem
Medina
Middletown
Maryville
Mecca
Campbell
Summit
Batesville
Covington
Jasper
Ashland
Milan
Manhattan
Butler
Quincy
Seaford
Hampton
Park City
York
Norwich
Oakdale
Centerville
Inwood
Altoona
Hastings
White Oak
Fairfield
Thomaston
Pomona
Benton
Robinson
Aberdeen
Auburn
Seminole
Brighton
Ogden
Berlin
Fairfax
Carbondale
San Antonio
Marshall
Happy Valley
Pinehurst
Monticello
Evergreen
Lake Shore
Dayton
Pulaski
Marion
Philadelphia
Highlands
Pembroke
Southgate
Richfield
Inverness
Yarmouth
Ashland
Franklin
Woodlake
Green
Salida
Wellington
New London
Perry
Middleton
Hempstead
Harrison
Marshfield
Santa Clara
Providence
Albertville
Clarkston
Jackson
Sandwich
Florence
Northport
Geneva
Torrington
Lowell
Smithville
Pleasantville
Huron
Inverness
St. Louis
Tyrone
Vandalia
Ephrata
Oakdale
Oak Grove
Milan
Gonzales
Hillsborough
Palmyra
Richland
Knoxville
Mantua
Springs
Rockville
Pacific
Rockport
Woodstock
Bedford
Lawrenceville
Crete
Sanger
St. Joseph
Independence
Ridgefield
Jackson
Collinsville
Highland Heights
Lewisburg
Fairview
Greenville
Syracuse
Franklin
Hillsboro
Stephenville
Maryborough
Rochester
Live Oak
Stratford
University Park
Centerville
Orange City
Mount Carmel
Kingston
Madison
Kiel
Ocean City
Commerce
Marion
Atherton
Bridge City
Ashland
Cottage Grove
Mendota
Huron
Allendale
Farmington
Milford
Sturgis
Perry
Russellville
North Bend
Kingsland
Mount Vernon
Bath
Litchfield
Cortland
Barrington
Parkville
Fort Meade
Twin Lakes
Junction City
Washington
Greenville
Bremen
Hamilton
Barberton
Portage
Nevada
Groveland
Roosevelt
South Hill
Columbia
Selma
Columbus
Canton
Spring Hill
Monticello
Beaver Dam
Sidney
Union
Lawrence
Irvington
Essex
Savage
Abilene
Decatur
Hillsboro
Lexington
Wharton
Belmont
Hurricane
Avon
Woodland
Litchfield
Powell
Bellwood
Geneseo
Milford
Bridgeport
Genoa
Keene
Eagle
Douglas
Salem
Emporia
St. John
California
Hampstead
Crystal Lake
Forest Hills
Mount Vernon
White Oak
Boonville
Richmond
Carthage
Walker
Riverside
Rockford
Sidney
Montgomery
Bridgeport
Ocean City
Buena Vista
Vineyard
Clinton
Valley Falls
Alpine
Piedmont
Chillicothe
Glenwood
Newport
Shrewsbury
Lewistown
Sheridan
Holly Springs
Ontario
Rensselaer
Twin Lakes
Bridgewater
Evansville
Vail
Grafton
Williamsburg
Rocky Mount
Darlington
Patterson
Carrollton
Henderson
Countryside
Jordan
Staunton
Progreso
Roseland
Taylor
Portland
Chester
Villa Park
Norwood
Union
Baldwin
Glendale
Luling
Delano
Independence
Grafton
Princeton
Kingston
New Castle
Carnarvon
Mansfield
Fairwood
Lebanon
Seminole
Belton
Benton
Greenwood
Alma
Anna
Pea Ridge
Nazareth
Greenacres
Princeton
Cumberland
Willard
Anthony
Webster
Fort Washington
Chelsea
Eureka
Ada
Taylorsville
Exeter
Charleston
Milton
Oxford
Waynesboro
Madisonville
Bowling Green
Greenwich
Lakeview
Sweetwater
Apple Valley
Jamestown
Germantown
Breckenridge
Roma
Waterville
Waterford
Nashville
Northfield
Brookhaven
Sparta
Warren
Salamanca
Dayton
Manchester
Titusville
Fairview
Lisbon
Rockwood
Brent
Trenton
Monticello
Glencoe
Jonesboro
Wayne
La Grange
Goshen
Paola
Highland
Caldwell
Byron
Cameron
Mount Carmel
Summit
Manchester
New Castle
Maplewood
Carlisle
St. Clair
Blaine
Salem
Centerville
Lafayette
Sunbury
Sunset
Red Oak
Jackson
Savannah
Mount Olive
Union City
Eaton
Spring Valley
Arlington Heights
Fruitland
Dumfries
Waynesville
Bangor
Collinsville
Avondale
Sidney
Springfield
Creve Coeur
Terryville
Mount Carmel
Central
Richmond
Dickinson
Forsyth
Oak Grove
Byron
Orange
Williamston
Ottawa
Lake City
Humboldt
Morris
Berkeley
Odessa
Montevideo
Abbeville
Springfield
Wildwood
Portland
South Haven
Gretna
Milan
Concordia
St. Joseph
Attica
Carrollton
Kings Park
Cleveland
Columbia
De Soto
Alexandria
Centreville
Bowie
Greenfield
River Ridge
Town and Country
Rutherford
Creston
Cochrane
La Paz
Liverpool
Melville
George Town
Jasper
Seymour
Clare
Saint-Georges
Scottsdale
Queenstown
Wyndham
Rodeo
Progress
Harrison
Newcastle
Valley Center
Celina
Glencoe
Franklin
Bloomfield
Woodbury
Hartford
Grand Rapids
Burlington
Hebron
Portland
Williston
Claremont
Dayton
Thompson
Sutton
Hastings
Redding
Freetown
Springfield
St. Marys
Woodbridge
Hobart
Lisbon
Barrington
Oak Grove
Marlborough
Douglas
Golden Valley
West Point
Mansfield
Concord
Dover
Rutland
Erwin
Freeport
Somers
Colorado City
Hernando
Brooklyn
Orono
Templeton
Hopkinton
Byram
Boston
Sterling
Lancaster
Wyoming
Onalaska
Woodstock
Greenfield
Charlestown
Piedmont
Halifax
Orange
Cumberland
Eden
Clarksville
Middlebury
Williamstown
Farmington
Chesterfield
Winslow
Richmond
Easton
Shirley
Westminster
Berwick
Kula
Buena Vista
Durham
Acton
Belmont
Lebanon
Fairview
New Albany
Pembroke
Batesville
Stow
Windsor
Peru
Newbury
Westbrook
Oak Ridge
Hanover
Millersville
Farmington
Wildwood
Parkville
Exeter
Hobart
Lincoln
Gateway
Plymouth
Lincoln
Dalton
Hamilton
Berkley
Trinity
Granby
Fairfield
Tecumseh
St. Francis
Pendleton
Harvard
West Point
Calverton
Sunnyvale
San Ramón
Fenton
Cairo
Medina
Peterborough
Marlborough
Newport
Lynchburg
Liberty
San Carlos
Granby
Dennis
Verona
Oakland
Jasper
Lebanon
Chatham
Kingston
Bathurst
Northfield
Southampton
Mendon
Logan
Hillsborough
Newberry
Dover
Corcoran
Littleton
Tewksbury
Woodstock
Lyndon
Mineola
Durham
Cambria
Lee
Dayton
Saratoga
Palermo
Gray
Wilmington
Winfield
Kirkwood
Gardiner
Greenville
Richland
Riga
Hopkinton
Warrenton
Atlanta
Independence
Bethany
Lyons
Barre
Rochester
Vienna
Columbia
Oneonta
Morristown
Loudon
Rye
Sterling
Ridgeland
Auburn
Alton
Holland
Hampstead
Warren
Hampden
Brookline
Hollywood
Bolton
Carlisle
Shelby
Glencoe
Paris
Newman
Colesville
Williamson
Wilton
Rockingham
Marion
Ulysses
Deerfield
Bristol
Manchester
McGregor
Clifton
Charlestown
Wakefield
Camargo
Marathon
La Cruz
Westport
Windsor
Deer Lake
Santa Bárbara
Shelburne
Anna Regina
San Lorenzo
El Dorado
Dondo
Peterborough
Geraldton
San Rafael
Winton
Santo António
Georgetown
Fort Smith
Hopedale
Richmond
Theodore
Ağdam
Island Lake

In [15]:
def non_ascii_cities():
    filtered_df = WC_DF[WC_DF['city'] != WC_DF['city_ascii']]
    cities = set(filtered_df['city'].values)
    return cities

non_ascii_cities()

{'Toltén',
 'Thiès',
 'Sfântu-Gheorghe',
 'Eiði',
 'Kérouané',
 'Samaná',
 'N’Djamena',
 'Ingeniero Guillermo N. Juárez',
 'Kamen’-na-Obi',
 'Béziers',
 'Kermān',
 'Ñacunday',
 'Hachiōji',
 'Sveti Jurij ob Ščavnici',
 'Štip',
 'Zābol',
 'Goianésia',
 'Paranaguá',
 'Ch’ŏngjin',
 'Guajará-Mirim',
 'Grudziądz',
 'Sonīpat',
 'Potosí',
 'Obleševo',
 'Murang’a',
 'Tômbua',
 'Kocēni',
 '‘Ajmān',
 'Gusinoozërsk',
 'Ciudad de Huajuapam de León',
 'Plzeň',
 'Shaḩḩāt',
 'Jyväskylä',
 'Zveçan',
 'Melitopol’',
 'Birgañj',
 'Al Fallūjah',
 'Río Gallegos',
 'Žabljak',
 'Bắc Giang',
 'Dahūk',
 'Trollhättan',
 'Mellieħa',
 'Dhangaḍhi̇̄',
 'Székesfehérvár',
 'Saïda',
 'Tərtər',
 'Hachimanchō',
 'Vyaz’ma',
 'Karūr',
 'Caacupé',
 'Ba‘qūbah',
 'Aračinovo',
 'Itaberaí',
 'Dubăsari',
 'Žetale',
 'Los Ángeles',
 'Nālūt',
 'Herāt',
 'Yên Bái',
 'Cap-Haïtien',
 'Għargħur',
 'Néma',
 'Gjøvik',
 'Trípoli',
 'Say’ūn',
 'Saint Ann’s Bay',
 'Al Ḩasakah',
 'Barra do Garças',
 'Changyŏn',
 'Nāsik',
 'Čaška',
 'Şa‘dah',
 'Rogašovci',
 'Roslavl’',
 'Malmö',
 'Tórshavn',
 'Río Grande',
 'Vevčani',
 'Sŏnbong',
 'Nek’emtē',
 'Sankt Pölten',
 'Añatuya',
 'Carúpano',
 'Santa Maria da Vitória',
 'San Cristóbal',
 'Vadsø',
 'Mitrovicë',
 'Mingəçevir',
 'Roboré',
 'Marabá',
 'Chiquinquirá',
 'Yaroslavl’',
 'Poljčane',
 'Jáltipan de Morelos',
 'Samandağ',
 'Curicó',
 'Bălţi',
 'Paysandú',
 'Cobán',
 'Łutselk’e',
 'São José dos Campos',
 'Évora',
 'Tržič',
 'Focşani',
 'Alexandroúpoli',
 'Győr',
 'Kramators’k',
 'Óbidos',
 'Al ‘Alamayn',
 'Fuglafjørður',
 'Tāngāil',
 'Zinjibār',
 'Mezen’',
 'Shar’ya',
 'Québec',
 'Aqtöbe',
 'Mişrātah',
 'Setúbal',
 'Toruń',
 'Gorišnica',
 'Brežice',
 'Shibīn al Kawm',
 'Banhā',
 'Birāṭnagar',
 'Cà Mau',
 'Ma’rib',
 'Perm’',
 'Al Kūt',
 'São Luís',
 'Šentjernej',
 'Concepción del Uruguay',
 'Negēlē',
 'Dajabón',
 'Bezwāda',
 'Jérémie',
 'Žužemberk',
 'Hamadān',
 'Şırnak',
 'La Unión',
 'Oğuz',
 'Ruše',
 'Haymā’',
 'Bīkaner',
 'Aḑ Ḑab‘ah',
 'Prokop’yevsk',
 'Şirvan',
 'Rača',
 'Berdyans’k',
 'Orël',
 'Gdańsk',
 'El’dikan',
 'N’dalatando',
 'Itajaí',
 'Çorovodë',
 'Ra’s al Khaymah',
 'Spassk-Dal’niy',
 'Marília',
 'Tuyên Quang',
 'Straža',
 'Ağdam',
 'Žagubica',
 'Kavála',
 'Halachó',
 'Ródos',
 'Garça',
 'Zākhū',
 'San José',
 'Črnomelj',
 'Calheta de São Miguel',
 'L’gov',
 'Simferopol’',
 'Črenšovci',
 'Divača',
 'Târgu Jiu',
 'Rečica ob Savinji',
 'Mandalī',
 'Mörön',
 'Maltahöhe',
 'Durrës',
 'Al ‘Uqaylah',
 'Villazón',
 'Thakhèk',
 'Juradó',
 'Växjö',
 'Biržai',
 'Piatra Neamţ',
 'Căuşeni',
 'Rugāji',
 'Gīmbī',
 'Karbalā’',
 'São Francisco do Sul',
 'Puerto Limón',
 'Paraíso',
 'Vänersborg',
 'Nyköping',
 'Colón',
 'Ning’an',
 'Taxco de Alarcón',
 'Valparaíso',
 'Hînceşti',
 'Astrakhan’',
 'Tamuín',
 'Elazığ',
 'Shāhrūd',
 'Zərdab',
 'Corumbá',
 'Skúvoy',
 'Spárti',
 'San Pedro de Macorís',
 'Coalcomán de Vázquez Pallares',
 'Kupiškis',
 'Jaú',
 'San Ramón de la Nueva Orán',
 'Tucuruí',
 'Gyêgu',
 'Uşak',
 'Fámjin',
 'Jõhvi',
 'Jequié',
 'Polatlı',
 'Lambaréné',
 'Gəncə',
 'Sežana',
 'Brăila',
 'Orūmīyeh',
 'Ålesund',
 'Atakpamé',
 'Saarbrücken',
 'Klaksvík',
 'Rājahmundry',
 'Pāvilosta',
 'Ciego de Ávila',
 'Villa Martín Colchak',
 'Torreón',
 'Tønsberg',
 'Mengeš',
 'Ísafjörður',
 'Lashkar Gāh',
 'Nāgpur',
 'Āsosa',
 'Beyləqan',
 'Qaşr al Farāfirah',
 'Aiguá',
 'Sabzevār',
 'Petatlán',
 'Söke',
 'Białystok',
 'Rače',
 'Zalău',
 'Veszprém',
 'Lübeck',
 'Neyshābūr',
 'Kārsava',
 'Al Manāqil',
 'Pájaros',
 'Viļaka',
 'Ćuprija',
 'Thái Bình',
 'Rørvik',
 'Codó',
 'Alatyr’',
 'Fu’an',
 'Minamiōzuma',
 'Hāgere Hiywet',
 'Āksum',
 'Nabatîyé',
 'Torbat-e Jām',
 'Bhiwāni',
 'Fushë Kosovë',
 'Neuquén',
 'Muğla',
 'Puerto López',
 'Irákleio',
 'Constitución',
 'Miragoâne',
 'Tver’',
 'Cəbrayıl',
 'Apače',
 'Ştefan Vodă',
 'Icó',
 'Andkhōy',
 'Trenčín',
 'Val-d’Or',
 'Constanţa',
 'Copiapó',
 'Xin’an',
 'Kpalimé',
 'Río Colorado',
 'Rîşcani',
 'São João da Boa Vista',
 'Pathānkot',
 'Kyŏngju',
 'Nar’yan-Mar',
 'São Tomé',
 'Delémont',
 'Ağstafa',
 'Ribeirão Prêto',
 'Bāglung',
 'Thủ Dầu Một',
 'Catalão',
 'Atoyac de Álvarez',
 'Al Qurayyāt',
 'Seinäjoki',
 'Moravče',
 'Kahramanmaraş',
 'Hà Tĩnh',
 'Wé',
 'Grajaú',
 'Shemonaīkha',
 'Ta’ Xbiex',
 'Šentjur',
 'Babušnica',
 'Dunaújváros',
 'Suharekë',
 'Sunch’ŏn',
 'Ust’-Kuyga',
 'Galaţi',
 'Zreče',
 'Sīkar',
 'Quinhámel',
 'Kelmė',
 'Taubaté',
 'Ar Rayyān',
 'Joaçaba',
 'Amrāvati',
 'An Cabhán',
 'Pinar del Río',
 'Hŭngnam',
 'Aţ Ţā’if',
 'Baghlān',
 'Širvintos',
 'Tomaž pri Ormožu',
 'Šilalė',
 'Macará',
 'Konče',
 'Pervoural’sk',
 'Ghāt',
 'Žabari',
 'Nevel’sk',
 'Būlaevo',
 'Żurrieq',
 'Thái Nguyên',
 'Khromtaū',
 'Goiânia',
 'Şūr',
 'Vị Thanh',
 'Aydın',
 'Ploieşti',
 'Mālegaon',
 'Ébolowa',
 'Béja',
 'Marawī',
 'Tacuarembó',
 'Castellón de la Plana',
 'Qal‘ah-ye Now',
 'Mohale’s Hoek',
 'Dezfūl',
 'Rokiškis',
 'Morón',
 'Borlänge',
 'Guaíra',
 'Makīnsk',
 'Pointe-à-Pitre',
 'Derzhavīnsk',
 'Zürich',
 'Telšiai',
 'Machilīpatnam',
 'Pul-e Khumrī',
 'Preševo',
 'Rrëshen',
 'Krāslava',
 'Anápolis',
 'Antsiran̈ana',
 'Saint John’s',
 'Aībak',
 'Chīrāla',
 'Poços de Caldas',
 'Ubá',
 'Khorramābād',
 'Ust’-Nyukzha',
 'Skrīveri',
 'San Ramón',
 'Araranguá',
 'Eirunepé',
 'Pećinci',
 'Ji-Paraná',
 'Jönköping',
 'Vlorë',
 'Severo-Kuril’sk',
 'Bač',
 'Ḩajjah',
 'Dīla',
 'Varėna',
 'Ngaoundéré',
 'Canatlán',
 'Aïn Sefra',
 'Río Mayo',
 'Ciudad Lázaro Cárdenas',
 'Balsadero Río Verde',
 'Straşeni',
 'Viļāni',
 'Qəbələ',
 'Kosjerić',
 'Dhamār',
 'Faīẕābād',
 'Al Qaşr',
 'Užice',
 'Mežica',
 'Sīwah',
 'Diyarbakır',
 'Tekirdağ',
 'Inírida',
 'Sovetskaya Gavan’',
 'Fürth',
 'Al ‘Aqabah',
 'Bacău',
 'Tébessa',
 'Brčko',
 'Ta‘izz',
 'Dhūlia',
 'Qŭrghonteppa',
 'Santo Tomás',
 'Vólos',
 'Radeče',
 'Šabac',
 'Qūchān',
 'Timbaúba',
 '‘Ibrī',
 'Juchitán de Zaragoza',
 'Covilhã',
 'Ivančna Gorica',
 'Chascomús',
 'Ludhiāna',
 'Marāgheh',
 'Santo Ângelo',
 'Farāh',
 'Lívingston',
 'Severoural’sk',
 'Ust’-Ilimsk',
 'Itambé',
 'Volčja Draga',
 'Floreşti',
 'Port Saint John’s',
 'Guamúchil',
 'Tillabéri',
 'Sørum',
 'Salgótarján',
 'Rondonópolis',
 'Abunã',
 'Västerås',
 'Irecê',
 'Akmenė',
 'Semič',
 'Belčišta',
 'Ciudad Guzmán',
 'Hanumānnagar',
 'Ấp Đa Lợi',
 'Shchëkino',
 'Guaratinguetá',
 'Ełk',
 'Şuşa',
 'Januária',
 'Pagėgiai',
 'Pančevo',
 'Liège',
 'Alīgarh',
 'Ust’-Ordynskiy',
 'Luján',
 'Batočina',
 'Bafoulabé',
 'Al Qaţīf',
 'Kukës',
 'Ar Ramādī',
 'Dembī Dolo',
 'Hamhŭng',
 'Odienné',
 'Sevastopol’',
 'Ersekë',
 'Hà Giang',
 'Botoşani',
 'Središče ob Dravi',
 'Ioánnina',
 'Sal’sk',
 'Ul’kan',
 'Bīdar',
 'Shashemenē',
 'Acapulco de Juárez',
 'Desē',
 'Ağsu',
 'Alausí',
 'N’Zérékoré',
 'Kattaqo‘rg‘on',
 'Qubadlı',
 'Satupa‘itea',
 'Heydərabad',
 'Ibrā’',
 'Atyraū',
 'Prešov',
 'Ayagöz',
 'Jirjā',
 'Svolvær',
 'Piteşti',
 'Pakxé',
 'Sūrat',
 'Ocniţa',
 'Sauðárkrókur',
 'Kürdəmir',
 'Bijāpur',
 'Concepción',
 'Liquiçá',
 'Örebro',
 'Ústí nad Labem',
 'San Pedro de Ycuamandiyú',
 'Roatán',
 'Godē',
 'Phan Thiết',
 'Jaboatão',
 'Sept-Îles',
 'Stari Trg pri Ložu',
 'Sansanné-Mango',
 'Raška',
 'Preiļi',
 'Tepelenë',
 'Sodražica',
 'Bački Petrovac',
 'Artëmovskiy',
 'Tobol’sk',
 'Ḩadībū',
 'Komotiní',
 'Mahābād',
 'Córdoba',
 'Kırklareli',
 'Krasnoural’sk',
 'Nikšić',
 'Edéa',
 'Sīrjān',
 'Şəki',
 'Khakhar’',
 'Quibdó',
 'Cataño',
 'Chapecó',
 'Butwāl',
 'Délįne',
 'Poznań',
 'Braşov',
 'Petrópolis',
 'Juárez',
 'Hāthras',
 'Eséka',
 'Siġġiewi',
 'Caracaraí',
 'Pukë',
 'Mirzāpur',
 'São Gabriel da Cachoeira',
 'Linköping',
 'Lào Cai',
 'Al Fayyūm',
 'Khōst',
 'Técpan de Galeana',
 'São José do Rio Prêto',
 'Cáceres',
 'Mytilíni',
 'Ārba Minch’',
 'Ciudad Nezahualcóyotl',
 'Bagé',
 'San Quintín',
 'Limbaži',
 'Dehra Dūn',
 'Arkhangel’sk',
 'Orocué',
 'Zárate',
 'Muş',
 'Viðareiði',
 'Lātūr',
 'Mūrmuiža',
 'L’viv',
 'Rūjiena',
 'P’yŏngsan',
 'Laçın',
 'Strenči',
 'Eşfahān',
 'Bījār',
 'Črna na Koroškem',
 'Ferreñafe',
 'Gümüşhane',
 'As Salţ',
 'Palmeira dos Índios',
 'Krško',
 'Ḩafar al Bāţin',
 'Al Minyā',
 'Estância',
 'Şuḩār',
 'Sokodé',
 'Crateús',
 'Šid',
 'Al’met’yevsk',
 'Coronel Suárez',
 'Bhāvnagar',
 'Požega',
 'Balakən',
 'Stavropol’',
 'Ropaži',
 'Nouméa',
 'Zāhedān',
 'Egilsstaðir',
 'Mallawī',
 'Açu',
 'Villa Constitución',
 'Würzburg',
 'Araxá',
 'Gießen',
 'Zanjān',
 'Pont-y-pŵl',
 'Lənkəran',
 'Ash Shiḩr',
 'Shibirghān',
 'Cárdenas',
 'Žitište',
 'Šmartno pri Litiji',
 'Kolhāpur',
 'Burhānpur',
 'Hödrögö',
 'Sayḩūt',
 'Ciudad Obregón',
 'Bollnäs',
 'Sāveh',
 'Mazatlán',
 'Noyabr’sk',
 'Dal’nerechensk',
 'Nazrēt',
 'Tehuacán',
 'Probištip',
 'Ağcabədi',
 'São João del Rei',
 'Jūrmala',
 'Labé',
 'Ivano-Frankivs’k',
 'Nev’yansk',
 'Arāk',
 'Fernandópolis',
 'Saint-Étienne',
 'Östersund',
 'Jamālpur',
 'Starše',
 'Kem’',
 'Araçatuba',
 'Al Jabīn',
 'Al ‘Arīsh',
 'Buôn Ma Thuột',
 'Varāmīn',
 'Jāzān',
 'Macapá',
 'Jaqué',
 'Guantánamo',
 'Angra do Heroísmo',
 'Tây Ninh',
 'Čajetina',
 'Guaxupé',
 'As Suwaydā’',
 'Gambēla',
 'Al Qāmishlī',
 'Pīlibhīt',
 'Minatitlán',
 'Laḩij',
 'Ciudad Cortés',
 'Cañon City',
 'Nuquí',
 'Šavnik',
 'Vitória',
 'Wrocław',
 'Bingöl',
 'Merošina',
 'Bol’sheretsk',
 'Popayán',
 'Shīeli',
 'Šalovci',
 'Pátra',
 'Mālpils',
 'Škofja Loka',
 'Al Bāḩah',
 'Ghardaïa',
 'Abdurahmoni Jomí',
 'Mataró',
 'Santa Inês',
 'Khmel’nyts’kyy',
 'Karnāl',
 'Sétif',
 'Kam”yanets’-Podil’s’kyy',
 'Pärnu',
 'Zelënodol’sk',
 'Tarīn Kōṯ',
 'Vaiņode',
 'Araguaína',
 'Saint-Jérôme',
 'Sārī',
 'Chŏngju',
 'Kök-Janggak',
 'Kamensk-Ural’skiy',
 'Safājā',
 'Bejaïa',
 'Tubarão',
 'Oktyabr’skiy',
 'Batī',
 'Đà Lạt',
 'Hưng Yên',
 'Cuauhtémoc',
 'Yélimané',
 'Palé',
 'Ōsaka',
 'Türkmenbaşy',
 'Jalālābād',
 'Đồng Hới',
 'Călăraşi',
 'Ibagué',
 'Lar’yak',
 'Nong’an',
 'Dəvəçi',
 'Saint Paul’s Bay',
 'Vilkaviškis',
 'Timişoara',
 'Jēkabpils',
 'Änew',
 'Río Bueno',
 'Caçador',
 'Porto Inglês',
 'Banī Suwayf',
 'Kvívík',
 'Gouré',
 'Bà Rịa',
 'Kamenicë',
 'Beočin',
 'Rivière-du-Loup',
 'Mārupe',
 'Alto Río Senguer',
 'Bāramūla',
 'Bhairāhawā',
 'Kishkeneköl',
 'Fdérik',
 'Anykščiai',
 'Niquelândia',
 'Priekuļi',
 'Adıyaman',
 'Tocantinópolis',
 'Bečej',
 'Peñuelas',
 'Cần Thơ',
 'Mazatán',
 'Bắc Ninh',
 'Cao Bằng',
 'Ürümqi',
 'Bodø',
 'Shtërpcë',
 'Banī Walīd',
 'Rostuša',
 'Īlām',
 'Tokār',
 'Gia Nghĩa',
 'Jumlā',
 'Zavrč',
 'Hải Dương',
 'Iğdır',
 'Veržej',
 'As Samāwah',
 'Gabú',
 'Ghāziābād',
 'Şoldăneşti',
 'Barnīs',
 'Tecomán',
 'Tam Kỳ',
 'Çorum',
 'Zlín',
 'Bərdə',
 'Kovel’',
 'Cēsis',
 'Fès',
 'Štore',
 'Żejtun',
 'Kateríni',
 'Podol’sk',
 'Deçan',
 'Bāmyān',
 'Jaén',
 'Kolār',
 'Kırıkkale',
 'Garzón',
 'Piraçununga',
 'Krasnotur’insk',
 'Türkistan',
 'Komsomol’sk-na-Amure',
 'Marsá Maţrūḩ',
 'Novobërdë',
 'Göyçay',
 'Dyat’kovo',
 'Ikšķile',
 'Nyíregyháza',
 'Zaječar',
 'Vecvārkava',
 'Anouvông',
 'Çankırı',
 'Klinë',
 'San Julián',
 'Bhāgalpur',
 'Itanhaém',
 'Puerto Aysén',
 'Siteía',
 'Macaé',
 'Godāwari̇̄',
 'Al Hufūf',
 'Santa Bárbara',
 'Araçuaí',
 'Zhangaözen',
 'Besançon',
 'Srīnagar',
 'Jhānsi',
 'Manatí',
 'Xocalı',
 'Maués',
 'Bhātpāra',
 'Acaraú',
 'Lysychans’k',
 'Târgovişte',
 'Niš',
 'Tāluqān',
 'Kökshetaū',
 'Autlán de Navarro',
 'Tatuí',
 'Borūjerd',
 'Švenčionys',
 'Juršinci',
 'La Cañada Flintridge',
 'Kŭlob',
 'Guntūr',
 'Vyshniy Volochëk',
 'An Nuhūd',
 'İzmir',
 'Ust’-Kamchatsk',
 'Fayrōz Kōh',
 'Bento Gonçalves',
 'Babanūsah',
 'Râmnicu Vâlcea',
 'Rāichūr',
 'Neuchâtel',
 'Kemijärvi',
 'Qarataū',
 'Mocímboa',
 'Ħamrun',
 'Qəzyan',
 'Sopište',
 'Ilha de Moçambique',
 'Barakī Barak',
 'Portimão',
 'Želino',
 'Koné',
 'Kəlbəcər',
 'P’ungsan',
 'Sumqayıt',
 'Ts’khinvali',
 'Xánthi',
 'Kākināda',
 'Usulután',
 'San José de las Lajas',
 'Čačak',
 'Villa O’Higgins',
 'Varaždin',
 'Hòa Bình',
 'Puerto Carreño',
 'Abéché',
 'Barisāl',
 'Elbląg',
 'Masjed Soleymān',
 'Shīrāz',
 'Šmarješke Toplice',
 'Ardabīl',
 'Bogué',
 'Inčukalns',
 'Joaquín V. González',
 'Nikopol’',
 'Al Qunayţirah',
 'Thanh Hóa',
 'Tân An',
 'Lạng Sơn',
 'Būrylbaytal',
 '‘Amrān',
 'Divinópolis',
 'Wādī Ḩalfā’',
 'Wŏnsan',
 'Hódmezővásárhely',
 'Gospić',
 'São Filipe',
 'Yong’an',
 'Tuluá',
 'Kawm Umbū',
 'Târgu-Mureş',
 'Trois-Rivières',
 'Füzuli',
 'Penonomé',
 'Nizāmābād',
 'Plungė',
 'Olenëk',
 'Salacgrīva',
 'Tauragė',
 'Šentilj',
 'Nīlī',
 'Beppuchō',
 'Capitão Poço',
 'Nova Varoš',
 'Nepālgañj',
 'Aḑ Ḑāli‘',
 'Semnān',
 'São José dos Pinhais',
 'Hämeenlinna',
 'Kaçanik',
 'Criciúma',
 'Mirbāţ',
 'Vitória da Conquista',
 'Hāora',
 'Rāmechhāp',
 'São José de Ribamar',
 'Aïn Temouchent',
 'Göygöl',
 'Rožaje',
 'Guayaramerín',
 'Chitré',
 'Rạch Giá',
 'Korçë',
 'Syzran’',
 'Al Ḩazm',
 'Medinīpur',
 'Nova Viçosa',
 'San Martín',
 'Podujevë',
 'Yi’an',
 'Santa Vitória do Palmar',
 'Chaniá',
 'Žilina',
 'Chānda',
 'Lüderitz',
 'Colíder',
 'San Ġiljan',
 'Tiruppūr',
 'Āwasa',
 'Iaşi',
 'Imġarr',
 'Brocēni',
 'Riebiņi',
 'Tauá',
 'Ghadāmis',
 'Al ‘Ayn',
 'Guéckédou',
 'Kraków',
 'Al Bayḑā’',
 'Culiacán',
 'Namp’o',
 'Totonicapán',
 'São Domingos',
 'Béni Mellal',
 'Ust’-Olenëk',
 'Siyəzən',
 'Al Khārijah',
 'Soubré',
 'Žiri',
 'São Paulo',
 'Ust’-Maya',
 'Morādābād',
 'Inđija',
 'Gabès',
 'Az Zaqāzīq',
 'San-Pédro',
 'Bouaké',
 'Kolašin',
 'Tiruvannāmalai',
 'Teleneşti',
 'Oriximiná',
 'Asyūţ',
 'Séguéla',
 'Ad Dammām',
 'Ḩā’il',
 'Léo',
 'Kruševo',
 'Nīca',
 'Ust’-Kut',
 'Asunción',
 'Al Ghayz̧ah',
 'Juanjuí',
 'Żebbuġ',
 'P’yŏngsŏng',
 'Fīrozābād',
 'Phônsavan',
 'Long Xuyên',
 'Qıvraq',
 'João Pessoa',
 'Uman’',
 'Anadyr’',
 'Tabrīz',
 'Maiquetía',
 'Abhā',
 'Orléans',
 'An Nāşirīyah',
 'Tefé',
 ...}

### B

There are several cities that have the same name. Write a function `num_cities_occurring_n_times(n)`, such that:
    
* The argument `n` is an integer;
* The returns an integer, which is the number of different city names that occur `n` times in the `worldcities` dataset. 
* The function should consider the city name to be the value in the `city` column. In other words the name in the form that may contain non-ASCII characters.

In [81]:
WC_DF

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
15488,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
15489,Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

In [99]:
# B
def num_cities_occurring_n_times(n):
    cities = []
    n_times = {}
    for i, row in WC_DF.iterrows():
        if row['city'] not in n_times:
            n_times[row['city']] = 1
        else:
            n_times[row['city']] += 1
    for city, v in n_times.items():
        if v == n:
            cities.append(city)
    return len(cities)

for i in range(20):
    print(i, num_cities_occurring_n_times(i))

0 0
1 12415
2 691
3 199
4 85
5 45
6 22
7 17
8 9
9 9
10 7
11 1
12 3
13 1
14 0
15 0
16 0
17 0
18 0
19 0

In [17]:
def num_cities_occurring_n_times(n):
    count_list = []
    num = 0
    city_list = []
    for city in WC_DF['city']:
        count = 0
        if city not in city_list:
            city_list.append(city)
            for repeat in WC_DF['city']: 
                if city == repeat:
                    count += 1
            count_list.append(count)
    for i in count_list:
        if i == n:
            num += 1
    return num

num_cities_occurring_n_times(2)

691

### C
Write a function `largest_cities_dataframe` that takes an `int` argument `n`  and uses the
pandas DataFrame `WC_DF` to return a new `DataFrame` containing `n` rows corresponding to
the `n` largest cities in terms of population size, in order of decreasing population size.

In [18]:
# C
def largest_cities_dataframe(n):


    return WC_DG_pop

In [100]:

def largest_cities_dataframe(n):
    WC_DF_pop = WC_DF.sort_values(by=["population"], ascending=False)[:n]
    return WC_DF_pop

largest_cities_dataframe(100)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
3,Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
4,São Paulo,Sao Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
95,Johannesburg,Johannesburg,-26.1700,28.0300,South Africa,ZA,ZAF,Gauteng,admin,3435000.0,1710550792
96,Berlin,Berlin,52.5218,13.4015,Germany,DE,DEU,Berlin,primary,3406000.0,1276451290
97,Algiers,Algiers,36.7631,3.0506,Algeria,DZ,DZA,Alger,primary,3354000.0,1012973369
98,Rome,Rome,41.8960,12.4833,Italy,IT,ITA,Lazio,primary,3339000.0,1380382862
99,Pyongyang,Pyongyang,39.0194,125.7547,"Korea, North",KP,PRK,P’yŏngyang,primary,3300000.0,1408738594

### D
Define a function `big_cities_in_country( country, population)` that takes as arguments a string corresponding to the name of a country and an integer, which will referes to a population number.
The function should return a `list` of the form 
<center>
    <tt>[("city1", pop1), ("city2", pop2),... ]</tt>, 
</center>

list should include only those cities whose population is greater than or equal to the given `popuplation` argument. The list should be ordered so that the `("cityN", popN)` items occur in **increasing** order of the population size `popN`.

In [20]:
# D
def big_cities_in_country(country, population):
    return result

In [21]:
def big_cities_in_country(country, population): # country is a string argument
    WC_DF_country = WC_DF[WC_DF['country'] == country] # new data frame of just cities in specified country
    a = WC_DF_country[WC_DF_country['population'] >= population] # data frame of cities over specified population in specified country
    a = a.sort_values(by=["population"], ascending=True)
    pop_list = list(a['population'])
    for i in range(len(pop_list)):
        pop_list[i] = int(pop_list[i])
    result = list(zip(list(a['city_ascii']), pop_list))
    return result

big_cities_in_country('United Kingdom', 1000000)

[('Glasgow', 1160000),
 ('Sheffield', 1292900),
 ('Leeds', 1529000),
 ('Manchester', 2230000),
 ('Birmingham', 2285000),
 ('London', 8567000)]

### E
Create a function that given a country name, returns an `int` which is the total population of 
people living in all the cities of that country, as given in `WC_DF`.

* ignore cities for which no population value is recorded in `WC_DF`. You will need to be able to deal with `NaN` values. A distinctive feature of `NaN` values is that they have been defined so that `x != x` has the value `True` if `x` has a `NaN` value.

In [22]:
# E
def country_total_cities_population(country):


    return pop

In [23]:
def country_total_cities_population(country):
    WC_DF_country = WC_DF[WC_DF['country'] == country]
    WC_DF_country = WC_DF_country.reset_index() # so index values run from 0 in specified country
    i=-1
    for p in WC_DF_country['population']:
        i+=1
        if p != p: # if NaN value
            WC_DF_country = WC_DF_country.drop(index = i) # remove city from data frame if no recorded population
    pop = int(sum(WC_DF_country['population']))
    return pop

country_total_cities_population('United Kingdom')

30846297